<?php
/**
 * COBOL_Rules vardefs
 */

if (!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$dictionary['COBOL_Rules'] = array(
    'table' => 'cobol_rules',
    'audited' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'id' => array(
            'name' => 'id',
            'vname' => 'LBL_ID',
            'type' => 'id',
            'required' => true,
            'reportable' => true,
        ),
        'name' => array(
            'name' => 'name',
            'vname' => 'LBL_NAME',
            'type' => 'name',
            'dbType' => 'varchar',
            'len' => '255',
            'unified_search' => true,
            'required' => true,
            'importable' => 'required',
        ),
        'date_entered' => array(
            'name' => 'date_entered',
            'vname' => 'LBL_DATE_ENTERED',
            'type' => 'datetime',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'date_modified' => array(
            'name' => 'date_modified',
            'vname' => 'LBL_DATE_MODIFIED',
            'type' => 'datetime',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'modified_user_id' => array(
            'name' => 'modified_user_id',
            'rname' => 'user_name',
            'id_name' => 'modified_user_id',
            'vname' => 'LBL_MODIFIED',
            'type' => 'assigned_user_name',
            'table' => 'users',
            'isnull' => 'false',
            'dbType' => 'id',
            'reportable' => true,
        ),
        'created_by' => array(
            'name' => 'created_by',
            'rname' => 'user_name',
            'id_name' => 'modified_user_id',
            'vname' => 'LBL_CREATED',
            'type' => 'assigned_user_name',
            'table' => 'users',
            'isnull' => 'false',
            'dbType' => 'id',
        ),
        'description' => array(
            'name' => 'description',
            'vname' => 'LBL_DESCRIPTION',
            'type' => 'text',
        ),
        'deleted' => array(
            'name' => 'deleted',
            'vname' => 'LBL_DELETED',
            'type' => 'bool',
            'default' => '0',
            'reportable' => false,
        ),
        'assigned_user_id' => array(
            'name' => 'assigned_user_id',
            'rname' => 'user_name',
            'id_name' => 'assigned_user_id',
            'vname' => 'LBL_ASSIGNED_TO_ID',
            'type' => 'relate',
            'table' => 'users',
            'module' => 'Users',
            'dbType' => 'id',
            'massupdate' => 0,
            'reportable' => true,
        ),
        'assigned_user_name' => array(
            'name' => 'assigned_user_name',
            'link' => 'assigned_user_link',
            'vname' => 'LBL_ASSIGNED_TO_NAME',
            'rname' => 'user_name',
            'type' => 'relate',
            'reportable' => false,
            'source' => 'non-db',
            'table' => 'users',
            'id_name' => 'assigned_user_id',
            'module' => 'Users',
            'duplicate_merge' => 'disabled',
        ),
        // Custom fields
        'rule_type' => array(
            'name' => 'rule_type',
            'vname' => 'LBL_RULE_TYPE',
            'type' => 'enum',
            'options' => 'cobol_rule_type_list',
            'len' => 100,
            'required' => true,
        ),
        'source_program_id' => array(
            'name' => 'source_program_id',
            'vname' => 'LBL_SOURCE_PROGRAM',
            'type' => 'id',
            'comment' => 'ID of the COBOL program this rule was extracted from',
        ),
        'rule_definition' => array(
            'name' => 'rule_definition',
            'vname' => 'LBL_RULE_DEFINITION',
            'type' => 'text',
            'comment' => 'Original rule definition extracted from COBOL',
        ),
        'visual_representation' => array(
            'name' => 'visual_representation',
            'vname' => 'LBL_VISUAL_REPRESENTATION',
            'type' => 'text',
            'comment' => 'JSON representation for visual editor',
        ),
        'conditions' => array(
            'name' => 'conditions',
            'vname' => 'LBL_CONDITIONS',
            'type' => 'text',
            'comment' => 'JSON array of rule conditions',
        ),
        'actions' => array(
            'name' => 'actions',
            'vname' => 'LBL_ACTIONS',
            'type' => 'text',
            'comment' => 'JSON array of rule actions',
        ),
        'priority' => array(
            'name' => 'priority',
            'vname' => 'LBL_PRIORITY',
            'type' => 'int',
            'default' => '50',
            'comment' => 'Rule execution priority (0-100)',
        ),
        'status' => array(
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'options' => 'cobol_rule_status_list',
            'len' => 100,
            'default' => 'active',
        ),
        'version' => array(
            'name' => 'version',
            'vname' => 'LBL_VERSION',
            'type' => 'varchar',
            'len' => '50',
            'default' => '1.0',
        ),
        'test_cases' => array(
            'name' => 'test_cases',
            'vname' => 'LBL_TEST_CASES',
            'type' => 'text',
            'comment' => 'JSON array of test cases',
        ),
        'generated_cobol' => array(
            'name' => 'generated_cobol',
            'vname' => 'LBL_GENERATED_COBOL',
            'type' => 'text',
            'comment' => 'COBOL code generated from visual editor',
        ),
        'is_modified' => array(
            'name' => 'is_modified',
            'vname' => 'LBL_IS_MODIFIED',
            'type' => 'bool',
            'default' => '0',
            'comment' => 'Has the rule been modified since extraction',
        ),
        'validation_status' => array(
            'name' => 'validation_status',
            'vname' => 'LBL_VALIDATION_STATUS',
            'type' => 'enum',
            'options' => 'cobol_validation_status_list',
            'len' => 100,
            'default' => 'pending',
        ),
    ),
    'relationships' => array(
        'cobol_rules_program' => array(
            'lhs_module' => 'COBOL_Programs',
            'lhs_table' => 'cobol_programs',
            'lhs_key' => 'id',
            'rhs_module' => 'COBOL_Rules',
            'rhs_table' => 'cobol_rules',
            'rhs_key' => 'source_program_id',
            'relationship_type' => 'one-to-many',
        ),
    ),
    'indices' => array(
        array('name' => 'cobol_rules_pk', 'type' => 'primary', 'fields' => array('id')),
        array('name' => 'idx_rule_type', 'type' => 'index', 'fields' => array('rule_type', 'deleted')),
        array('name' => 'idx_status', 'type' => 'index', 'fields' => array('status', 'deleted')),
        array('name' => 'idx_source_program', 'type' => 'index', 'fields' => array('source_program_id')),
    ),
);
?>