<?php
/**
 * COBOL_Programs vardefs
 */

if (!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$dictionary['COBOL_Programs'] = array(
    'table' => 'cobol_programs',
    'audited' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'id' => array(
            'name' => 'id',
            'vname' => 'LBL_ID',
            'type' => 'id',
            'required' => true,
            'reportable' => true,
            'comment' => 'Unique identifier',
        ),
        'name' => array(
            'name' => 'name',
            'vname' => 'LBL_NAME',
            'type' => 'name',
            'dbType' => 'varchar',
            'len' => '255',
            'unified_search' => true,
            'required' => true,
            'importable' => 'required',
        ),
        'date_entered' => array(
            'name' => 'date_entered',
            'vname' => 'LBL_DATE_ENTERED',
            'type' => 'datetime',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'date_modified' => array(
            'name' => 'date_modified',
            'vname' => 'LBL_DATE_MODIFIED',
            'type' => 'datetime',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'modified_user_id' => array(
            'name' => 'modified_user_id',
            'rname' => 'user_name',
            'id_name' => 'modified_user_id',
            'vname' => 'LBL_MODIFIED',
            'type' => 'assigned_user_name',
            'table' => 'users',
            'isnull' => 'false',
            'dbType' => 'id',
            'reportable' => true,
        ),
        'created_by' => array(
            'name' => 'created_by',
            'rname' => 'user_name',
            'id_name' => 'modified_user_id',
            'vname' => 'LBL_CREATED',
            'type' => 'assigned_user_name',
            'table' => 'users',
            'isnull' => 'false',
            'dbType' => 'id',
        ),
        'description' => array(
            'name' => 'description',
            'vname' => 'LBL_DESCRIPTION',
            'type' => 'text',
        ),
        'deleted' => array(
            'name' => 'deleted',
            'vname' => 'LBL_DELETED',
            'type' => 'bool',
            'default' => '0',
            'reportable' => false,
        ),
        'assigned_user_id' => array(
            'name' => 'assigned_user_id',
            'rname' => 'user_name',
            'id_name' => 'assigned_user_id',
            'vname' => 'LBL_ASSIGNED_TO_ID',
            'type' => 'relate',
            'table' => 'users',
            'module' => 'Users',
            'dbType' => 'id',
            'massupdate' => 0,
            'reportable' => true,
        ),
        'assigned_user_name' => array(
            'name' => 'assigned_user_name',
            'link' => 'assigned_user_link',
            'vname' => 'LBL_ASSIGNED_TO_NAME',
            'rname' => 'user_name',
            'type' => 'relate',
            'reportable' => false,
            'source' => 'non-db',
            'table' => 'users',
            'id_name' => 'assigned_user_id',
            'module' => 'Users',
            'duplicate_merge' => 'disabled',
        ),
        // Custom fields
        'program_code' => array(
            'name' => 'program_code',
            'vname' => 'LBL_PROGRAM_CODE',
            'type' => 'text',
            'comment' => 'The actual COBOL program code',
        ),
        'program_type' => array(
            'name' => 'program_type',
            'vname' => 'LBL_PROGRAM_TYPE',
            'type' => 'enum',
            'options' => 'cobol_program_type_list',
            'len' => 100,
            'default' => 'credit',
        ),
        'last_execution' => array(
            'name' => 'last_execution',
            'vname' => 'LBL_LAST_EXECUTION',
            'type' => 'datetime',
        ),
        'execution_count' => array(
            'name' => 'execution_count',
            'vname' => 'LBL_EXECUTION_COUNT',
            'type' => 'int',
            'default' => '0',
        ),
        'average_runtime' => array(
            'name' => 'average_runtime',
            'vname' => 'LBL_AVERAGE_RUNTIME',
            'type' => 'float',
            'precision' => 3,
            'comment' => 'Average runtime in seconds',
        ),
        'status' => array(
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'options' => 'cobol_program_status_list',
            'len' => 100,
            'default' => 'active',
        ),
        'version' => array(
            'name' => 'version',
            'vname' => 'LBL_VERSION',
            'type' => 'varchar',
            'len' => '50',
        ),
        'input_parameters' => array(
            'name' => 'input_parameters',
            'vname' => 'LBL_INPUT_PARAMETERS',
            'type' => 'text',
            'comment' => 'JSON schema of input parameters',
        ),
        'output_format' => array(
            'name' => 'output_format',
            'vname' => 'LBL_OUTPUT_FORMAT',
            'type' => 'text',
            'comment' => 'JSON schema of output format',
        ),
        'error_count' => array(
            'name' => 'error_count',
            'vname' => 'LBL_ERROR_COUNT',
            'type' => 'int',
            'default' => '0',
        ),
        'success_rate' => array(
            'name' => 'success_rate',
            'vname' => 'LBL_SUCCESS_RATE',
            'type' => 'float',
            'precision' => 2,
            'default' => '100',
            'comment' => 'Success rate percentage',
        ),
    ),
    'relationships' => array(),
    'indices' => array(
        array('name' => 'cobol_programs_pk', 'type' => 'primary', 'fields' => array('id')),
        array('name' => 'idx_program_type', 'type' => 'index', 'fields' => array('program_type', 'deleted')),
        array('name' => 'idx_status', 'type' => 'index', 'fields' => array('status', 'deleted')),
    ),
);
?>