apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: suitecrm-cobol
type: Opaque
stringData:
  DB_HOST: "mysql-primary.suitecrm-cobol.svc.cluster.local"
  DB_NAME: "suitecrm"
  DB_USER: "suitecrm"
  DB_PASSWORD: "CHANGE_ME_PRODUCTION_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: suitecrm-cobol
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME_PRODUCTION_JWT_SECRET"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: suitecrm-cobol
type: Opaque
stringData:
  REDIS_PASSWORD: "CHANGE_ME_PRODUCTION_REDIS_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: suitecrm-cobol
type: Opaque
stringData:
  GRAFANA_PASSWORD: "CHANGE_ME_PRODUCTION_GRAFANA_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-secret
  namespace: suitecrm-cobol
type: Opaque
stringData:
  ELASTIC_PASSWORD: "CHANGE_ME_PRODUCTION_ELASTIC_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
  namespace: suitecrm-cobol
type: Opaque
stringData:
  SMTP_HOST: "smtp.example.com"
  SMTP_USER: "notifications@example.com"
  SMTP_PASSWORD: "CHANGE_ME_SMTP_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-secret
  namespace: suitecrm-cobol
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "CHANGE_ME_AWS_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "CHANGE_ME_AWS_SECRET_KEY"
  BACKUP_S3_BUCKET: "suitecrm-cobol-backups"
  BACKUP_ENCRYPTION_KEY: "CHANGE_ME_BACKUP_ENCRYPTION_KEY"
---
apiVersion: v1
kind: Secret
metadata:
  name: mainframe-secret
  namespace: suitecrm-cobol
type: Opaque
stringData:
  MAINFRAME_HOST: "mainframe.example.com"
  MAINFRAME_USER: "cobol_user"
  MAINFRAME_PASSWORD: "CHANGE_ME_MAINFRAME_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: ssl-certificate
  namespace: suitecrm-cobol
type: kubernetes.io/tls
data:
  # Base64 encoded certificate and key - REPLACE WITH ACTUAL CERTIFICATES
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t