apiVersion: v1
kind: Service
metadata:
  name: suitecrm
  namespace: suitecrm-cobol
  labels:
    app: suitecrm
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: suitecrm
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: suitecrm
  namespace: suitecrm-cobol
  labels:
    app: suitecrm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: suitecrm
  template:
    metadata:
      labels:
        app: suitecrm
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - suitecrm
              topologyKey: kubernetes.io/hostname
      containers:
      - name: suitecrm
        image: ${DOCKER_REGISTRY}/suitecrm-cobol-bridge:${VERSION}
        ports:
        - containerPort: 80
          name: http
        env:
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DB_HOST
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DB_NAME
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DB_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DB_PASSWORD
        - name: REDIS_HOST
          value: "redis-master"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD
        envFrom:
        - configMapRef:
            name: suitecrm-config
        volumeMounts:
        - name: suitecrm-data
          mountPath: /var/www/html
        - name: suitecrm-uploads
          mountPath: /var/www/html/upload
        - name: suitecrm-cache
          mountPath: /var/www/html/cache
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 33
          runAsGroup: 33
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: suitecrm-data
        persistentVolumeClaim:
          claimName: suitecrm-data-pvc
      - name: suitecrm-uploads
        persistentVolumeClaim:
          claimName: suitecrm-uploads-pvc
      - name: suitecrm-cache
        emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suitecrm-data-pvc
  namespace: suitecrm-cobol
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "efs"
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suitecrm-uploads-pvc
  namespace: suitecrm-cobol
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "efs"
  resources:
    requests:
      storage: 100Gi